#! /usr/bin/env php

<?php
error_reporting(E_ALL);
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}


$app = new Symfony\Component\Console\Application('Static Sites', '0.1');
$app->add(new StaticSites\Console\RunCommand);
$app->add(new StaticSites\Console\MakeCommand);

// Dev Only
$app->add(new StaticSites\Console\TestCommand);

$app->run();